In [26]:
import numpy as np


def dist(x1, y1, x2, y2):
    return np.sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2)

def recalculate_centers(x, y, F, m, c):
    c_x = c_y = [0] * c
    for i in range(c):
        sum_1_x = 0
        sum_2 = 0
        sum_1_y = 0
        for k in range(len(x)):
            sum_1_x += (F[k][i]**m) * x[k]
            sum_1_y += (F[k][i]**m) * y[k]
            sum_2 += F[k][i]**m
        c_x[i] = sum_1_x / sum_2
        c_x[i]= sum_1_y / sum_2
    return c_x, c_y

def recalculate_distances(x, y, c_x, c_y, c, M):
    D = [[0]*c for i in range(M)]
    for k in range(M):
        for i in range(c):
            D[k][i] = dist(x[k], y[k], c_x[i], c_y[i])
#     print(np.array(D))
#     print('\n\n')
    return D

def recalculate_degree(c, M, D, m):
    # Высчитываем степень принадлежности точек кластерам
    F = [[0]*c for i in range(M)] # матрица разбиения
    for k in range(M):
        for i in range(c):
            sum = 0
            for j in range(c):
                sum += (D[k][i] / D[k][j])**(2/m - 1)
            F[k][i] = round(1.0 / sum, 2)
    print(np.array(F))
    print('\n\n')
    return F

def check_matrix_convergence(M, c, F, prev_F, epsilon):
    max = 0
    for k in range(M):
        for i in range(c):
            temp = abs(F[k][i] - prev_F[k][i])
            if temp > max:
                max = temp
    if max < epsilon:
        return True
    return False

def c_means(x, y, c, M, m, epsilon):
    print('iter #1')
    # Случайным образом задаем центры кластеров
    prev_centers_x = np.random.randint(1, 100, c)
    prev_centers_y = np.random.randint(1, 100, c)
#     print(prev_centers_x, prev_centers_y)
#     print('\n\n')
    
    # Высчитываем расстояния между точками и центрами кластеров
    prev_D = recalculate_distances(x, y, prev_centers_x, prev_centers_y, c, M)
    
    # Высчитываем степень принадлежности точек кластерам
    prev_F = recalculate_degree(c, M, prev_D, m)
    
    # Уточняем элементы матрицы F, пока алгоритм не сойдется к матрице
    iter_cnt = 2
    while True:
        print(f'iter #{iter_cnt}')
        centers_x, centers_y = recalculate_centers(x, y, prev_F, m, c)
        D = recalculate_distances(x, y, centers_x, centers_y, c, M)
        F = recalculate_degree(c, M, D, m)
        if check_matrix_convergence(M, c, F, prev_F, epsilon):
            break
        else:
            prev_centers_x = centers_x
            prev_centers_y = centers_y
            prev_D = D
            prev_F = F
            iter_cnt += 1
    

def main():
    epsilon = 0.1
    M = 100
    m = 0.1
    c = 3

    x = np.random.randint(1, 100, M)
    y = np.random.randint(1, 100, M)
#     print(x)
#     print(y)
#     print('\n\n')
    
    result = c_means(x, y, c, M, m, epsilon)

main()


iter #1
[[0.   0.   1.  ]
 [1.   0.   0.  ]
 [1.   0.   0.  ]
 [0.97 0.01 0.02]
 [1.   0.   0.  ]
 [1.   0.   0.  ]
 [0.   0.   1.  ]
 [0.   0.97 0.03]
 [0.25 0.22 0.54]
 [0.   0.   1.  ]
 [1.   0.   0.  ]
 [0.91 0.09 0.  ]
 [0.01 0.85 0.14]
 [0.   1.   0.  ]
 [0.   0.01 0.99]
 [1.   0.   0.  ]
 [0.01 0.96 0.03]
 [0.   0.02 0.98]
 [0.   1.   0.  ]
 [0.   0.   1.  ]
 [0.   1.   0.  ]
 [0.   0.02 0.98]
 [0.08 0.89 0.03]
 [1.   0.   0.  ]
 [0.   1.   0.  ]
 [0.   1.   0.  ]
 [0.   0.14 0.86]
 [0.   0.2  0.79]
 [0.   0.   1.  ]
 [0.   0.   1.  ]
 [1.   0.   0.  ]
 [0.   0.05 0.95]
 [1.   0.   0.  ]
 [1.   0.   0.  ]
 [0.   0.13 0.87]
 [0.   0.01 0.99]
 [0.   0.08 0.92]
 [1.   0.   0.  ]
 [1.   0.   0.  ]
 [0.88 0.1  0.02]
 [0.98 0.01 0.01]
 [0.   0.4  0.6 ]
 [0.   0.1  0.9 ]
 [0.   0.   1.  ]
 [1.   0.   0.  ]
 [0.   1.   0.  ]
 [1.   0.   0.  ]
 [1.   0.   0.  ]
 [0.   0.   1.  ]
 [1.   0.   0.  ]
 [0.56 0.11 0.33]
 [1.   0.   0.  ]
 [0.   0.   1.  ]
 [1.   0.   0.  ]
 [0.58 0.1  0.32]
 [